services:
  europe:
    image: webapi
    container_name: europe-api
    build:
      context: .
      dockerfile: webapi/Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"
    environment:
      - NODE_ID=1

  asia:
    image: webapi
    container_name: asia-api
    build:
      context: .
      dockerfile: webapi/Dockerfile
    ports:
      - "6000:6000"
      - "6001:6001"
    environment:
      - NODE_ID=2
        
  redis:
    image: redis
    container_name: cache
    ports:
      - "6379:6379"
              
  keycloak:
    image: quay.io/keycloak/keycloak:26.2.5
    ports:
      - "8080:8080"
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    command: start-dev